# Generated by Django 5.2.1 on 2025-06-08 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={},
        ),
        migrations.AlterModelOptions(
            name='donation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={},
        ),
    ]
